### ISSUE TITLE
Unable to access API when Site Offline component is enabled

### ISSUE THREAD

**Issue by mirabledictu** [opensource-socialnetwork/OssnServices#13]
Hi, is there a way to enable api access when site offline component is used?

Thanks.

**Comment by lianglee** [comment]
I think this will same happens with Private Network component this need to be resolved soon.

**Comment by wobsoriano** [comment]
> I think this will same happens with Private Network component this need to be resolved soon.

Any updates to this? It's blocking some of the photos like the photos from wall posts

`https://test.com/post/photo/127186/a896aad913b9f5c59ea40a8c778f6b02.jpeg` 

Here's the response of that image when clicked on the network tab

<img width="412" alt="Screen Shot 2022-05-07 at 10 26 16 AM" src="https://user-images.githubusercontent.com/13049130/167265344-382e755e-61f3-4811-bc02-2b996ecfb122.png">

It redirects to the login page because of the private network. It returns this error - `com:private:network:deney`

**Comment by lianglee** [comment]
Fixed issue with Private Network please use 8.1 version OSSN services.  Site offline issue can not be fixed.  Its is for taking the site completely offline.
